// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shortener.Data;

namespace Shortener.Migrations
{
    [DbContext(typeof(PasteContext))]
    [Migration("20230917190723_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shortener.Data.Paste", b =>
                {
                    b.Property<int>("PasteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("Expires")
                        .HasColumnType("int");

                    b.Property<string>("Shortlink")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PasteId");

                    b.HasIndex("Shortlink")
                        .IsUnique()
                        .HasFilter("[Shortlink] IS NOT NULL");

                    b.ToTable("Pastes");
                });
#pragma warning restore 612, 618
        }
    }
}
