POST {{scheme}}{{host}}:{{port}}/shorten
Content-Type: application/json

{
  "content": "expires in a week",
  "expires": 10080
}

###

POST {{scheme}}{{host}}:{{port}}/shorten
Content-Type: application/json

{
  "content": "expires soon",
  "expires": 0
}

###

POST {{scheme}}{{host}}:{{port}}/shorten
Accept: application/json
Content-Type: application/json

{
  "content": "",
  "expires": 60
}

###

POST {{scheme}}{{host}}:{{port}}/shorten
Accept: application/json
Content-Type: application/json

{
  "status": "fail - 'content' field is missing",
  "expires": 60
}

###

POST {{scheme}}{{host}}:{{port}}/shorten
Accept: application/json
Content-Type: application/json

{
  "content": "80-minute expiration",
  "expires": 80
}

###

POST {{scheme}}{{host}}:{{port}}/shorten
Accept: application/json
Content-Type: application/json

{
  "content": "without expiration"
}