apiVersion: apps/v1
kind: Deployment
metadata:
  name: lengthener
  labels:
    app: lengthener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lengthener
  template:
    metadata:
      name: lengthener
      labels:
        app: lengthener
    spec:
      containers:
        - name: lengthener
          image: lengthener
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lengthener
spec:
  selector:
    app: lengthener
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 80
  type: NodePort
